name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  cross-test:
      name: '${{ matrix.os }}: build and test'
      runs-on: '${{ matrix.os }}'
      strategy:
        fail-fast: false
        matrix:
          os: [windows-latest, ubuntu-latest, macos-latest, ubuntu-20.04]
          python-version: [3.8]
      
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Building interpreter
          run: cmake CMAKE_BUILD_TYPE=Release CMakeLists.txt; cmake --build ./
        - name: Run tests
          run: cd tests; python test.py; cd ".."
